checks:
    php: true

filter:
    paths:
        - "src/*"

build:
    image: default-bionic

    environment:
        php:
            version: 7.4
            ini:
                xdebug.mode: coverage

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

        tests:
            dependencies:
                override:
                    - composer self-update
                    - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            tests:
                override:
                    - command: |
                          php ./vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover=coverage.clover
                      idle_timeout: 600    # 10 minutes
                      on_node: 1
                      coverage:
                          file: coverage.clover
                          format: php-clover
